# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
      - name: iris-api-container
        image: __IMAGE_TAG__ # This placeholder will be updated by your CI/CD pipeline
        ports:
        - containerPort: 8000
        # Ensure this block has the correct indentation
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
